# Generated by Django 3.2.8 on 2021-11-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_message_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
